const sections = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly (name, email, payment details) and information generated by your use of the service, such as watch history, device type, and IP address.",
  },
  {
    title: "2. How We Use Your Information",
    body: "We use your information to provide and improve the service, process payments, personalize recommendations, send service-related communications, and maintain platform security.",
  },
  {
    title: "3. Cookies & Tracking",
    body: "Novel TV uses cookies and similar technologies to keep you signed in, remember preferences, and understand how the service is used. You can control cookies through your browser settings.",
  },
  {
    title: "4. How We Share Information",
    body: "We share information with service providers who help us operate Novel TV (payment processing, video delivery, analytics) under confidentiality obligations. We do not sell your personal information.",
  },
  {
    title: "5. Data Security",
    body: "We use industry-standard safeguards to protect your information, including encrypted connections and access controls. No system is completely secure, so we encourage strong, unique passwords.",
  },
  {
    title: "6. Your Rights & Choices",
    body: "Depending on your location, you may have the right to access, correct, export, or delete your personal information. You can manage most of this directly from your account settings, or contact us for assistance.",
  },
  {
    title: "7. Children's Privacy",
    body: "Novel TV is not directed at children under 13, and we do not knowingly collect personal information from them.",
  },
  {
    title: "8. Changes to This Policy",
    body: "We may update this Privacy Policy periodically. Material changes will be communicated before they take effect.",
  },
  {
    title: "9. Contact Us",
    body: "Questions about this policy or your data? Reach us through the Contact Us page.",
  },
];

export default function PrivacyPolicyPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-10">
      <h1 className="font-heading text-5xl uppercase text-text-primary sm:text-6xl">
        Privacy Policy
      </h1>
      <p className="mt-2 font-body text-sm text-text-muted">
        Last updated: January 1, 2026
      </p>

      <p className="mt-6 font-body text-text-secondary">
        This Privacy Policy explains how Novel TV collects, uses, and protects
        your information. This is placeholder text for development purposes
        — replace with reviewed legal copy before launch.
      </p>

      <div className="mt-8 space-y-8">
        {sections.map((section) => (
          <div key={section.title}>
            <h2 className="font-ui text-lg font-semibold text-text-primary">
              {section.title}
            </h2>
            <p className="mt-2 font-body text-sm leading-relaxed text-text-secondary">
              {section.body}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}
